"""esquema base

Revision ID: 0001
Revises:
Create Date: 2026-10-05 22:34:12.226732

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "negocios",
        sa.Column("id_negocio", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id_negocio", name=op.f("pk_negocios")),
    )
    op.create_table(
        "categorias",
        sa.Column("id_categoria", sa.Integer(), nullable=False),
        sa.Column("id_negocio", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=80), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.ForeignKeyConstraint(
            ["id_negocio"], ["negocios.id_negocio"], name=op.f("fk_categorias_id_negocio_negocios")
        ),
        sa.PrimaryKeyConstraint("id_categoria", name=op.f("pk_categorias")),
        sa.UniqueConstraint("id_negocio", "nombre", name=op.f("uq_categorias_id_negocio_nombre")),
    )
    op.create_index(op.f("ix_categorias_id_negocio"), "categorias", ["id_negocio"], unique=False)
    op.create_table(
        "clientes",
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column("id_negocio", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("telefono", sa.String(length=20), nullable=True),
        sa.Column(
            "limite_credito", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column("acepta_whatsapp", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "NOT acepta_whatsapp OR telefono IS NOT NULL",
            name=op.f("ck_clientes_whatsapp_requiere_telefono"),
        ),
        sa.CheckConstraint("limite_credito >= 0", name=op.f("ck_clientes_limite_positivo")),
        sa.ForeignKeyConstraint(
            ["id_negocio"], ["negocios.id_negocio"], name=op.f("fk_clientes_id_negocio_negocios")
        ),
        sa.PrimaryKeyConstraint("id_cliente", name=op.f("pk_clientes")),
    )
    op.create_index(op.f("ix_clientes_id_negocio"), "clientes", ["id_negocio"], unique=False)
    op.create_table(
        "usuarios",
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("id_negocio", sa.Integer(), nullable=False),
        sa.Column("nombre", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("rol", sa.String(length=20), nullable=False),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint("rol IN ('dueno', 'cajero')", name=op.f("ck_usuarios_rol_valido")),
        sa.ForeignKeyConstraint(
            ["id_negocio"], ["negocios.id_negocio"], name=op.f("fk_usuarios_id_negocio_negocios")
        ),
        sa.PrimaryKeyConstraint("id_usuario", name=op.f("pk_usuarios")),
        sa.UniqueConstraint("email", name=op.f("uq_usuarios_email")),
    )
    op.create_index(op.f("ix_usuarios_id_negocio"), "usuarios", ["id_negocio"], unique=False)
    op.create_table(
        "productos",
        sa.Column("id_producto", sa.Integer(), nullable=False),
        sa.Column("id_negocio", sa.Integer(), nullable=False),
        sa.Column("id_categoria", sa.Integer(), nullable=True),
        sa.Column("nombre", sa.String(length=120), nullable=False),
        sa.Column("codigo_barras", sa.String(length=50), nullable=True),
        sa.Column("unidad_medida", sa.String(length=10), server_default="unidad", nullable=False),
        sa.Column("precio_venta", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "precio_costo", sa.Numeric(precision=12, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "stock_actual", sa.Numeric(precision=10, scale=3), server_default="0", nullable=False
        ),
        sa.Column(
            "stock_minimo", sa.Numeric(precision=10, scale=3), server_default="0", nullable=False
        ),
        sa.Column("activo", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "unidad_medida IN ('unidad', 'libra', 'onza', 'litro')",
            name=op.f("ck_productos_unidad_valida"),
        ),
        sa.CheckConstraint(
            "precio_venta >= 0 AND precio_costo >= 0", name=op.f("ck_productos_precios_positivos")
        ),
        sa.ForeignKeyConstraint(
            ["id_categoria"],
            ["categorias.id_categoria"],
            name=op.f("fk_productos_id_categoria_categorias"),
        ),
        sa.ForeignKeyConstraint(
            ["id_negocio"], ["negocios.id_negocio"], name=op.f("fk_productos_id_negocio_negocios")
        ),
        sa.PrimaryKeyConstraint("id_producto", name=op.f("pk_productos")),
        sa.UniqueConstraint(
            "id_negocio", "codigo_barras", name=op.f("uq_productos_id_negocio_codigo_barras")
        ),
    )
    op.create_index(op.f("ix_productos_id_categoria"), "productos", ["id_categoria"], unique=False)
    op.create_index(op.f("ix_productos_id_negocio"), "productos", ["id_negocio"], unique=False)
    op.create_index(op.f("ix_productos_nombre"), "productos", ["nombre"], unique=False)
    op.create_table(
        "ventas",
        sa.Column("id_venta", sa.Integer(), nullable=False),
        sa.Column("id_negocio", sa.Integer(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("id_cliente", sa.Integer(), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("metodo_pago", sa.String(length=15), nullable=False),
        sa.Column("estado", sa.String(length=15), server_default="completada", nullable=False),
        sa.CheckConstraint(
            "estado IN ('completada', 'anulada')", name=op.f("ck_ventas_estado_valido")
        ),
        sa.CheckConstraint(
            "metodo_pago <> 'fiao' OR id_cliente IS NOT NULL",
            name=op.f("ck_ventas_fiao_requiere_cliente"),
        ),
        sa.CheckConstraint(
            "metodo_pago IN ('efectivo', 'tarjeta', 'transferencia', 'fiao')",
            name=op.f("ck_ventas_metodo_pago_valido"),
        ),
        sa.CheckConstraint("total >= 0", name=op.f("ck_ventas_total_positivo")),
        sa.ForeignKeyConstraint(
            ["id_cliente"], ["clientes.id_cliente"], name=op.f("fk_ventas_id_cliente_clientes")
        ),
        sa.ForeignKeyConstraint(
            ["id_negocio"], ["negocios.id_negocio"], name=op.f("fk_ventas_id_negocio_negocios")
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"], ["usuarios.id_usuario"], name=op.f("fk_ventas_id_usuario_usuarios")
        ),
        sa.PrimaryKeyConstraint("id_venta", name=op.f("pk_ventas")),
    )
    op.create_index(op.f("ix_ventas_fecha"), "ventas", ["fecha"], unique=False)
    op.create_index(op.f("ix_ventas_id_cliente"), "ventas", ["id_cliente"], unique=False)
    op.create_index(op.f("ix_ventas_id_negocio"), "ventas", ["id_negocio"], unique=False)
    op.create_index(op.f("ix_ventas_id_usuario"), "ventas", ["id_usuario"], unique=False)
    op.create_table(
        "detalle_venta",
        sa.Column("id_detalle", sa.Integer(), nullable=False),
        sa.Column("id_venta", sa.Integer(), nullable=False),
        sa.Column("id_producto", sa.Integer(), nullable=False),
        sa.Column("cantidad", sa.Numeric(precision=10, scale=3), nullable=False),
        sa.Column("precio_unitario", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.CheckConstraint("cantidad > 0", name=op.f("ck_detalle_venta_cantidad_positiva")),
        sa.ForeignKeyConstraint(
            ["id_producto"],
            ["productos.id_producto"],
            name=op.f("fk_detalle_venta_id_producto_productos"),
        ),
        sa.ForeignKeyConstraint(
            ["id_venta"], ["ventas.id_venta"], name=op.f("fk_detalle_venta_id_venta_ventas")
        ),
        sa.PrimaryKeyConstraint("id_detalle", name=op.f("pk_detalle_venta")),
    )
    op.create_index(
        op.f("ix_detalle_venta_id_producto"), "detalle_venta", ["id_producto"], unique=False
    )
    op.create_index(op.f("ix_detalle_venta_id_venta"), "detalle_venta", ["id_venta"], unique=False)
    op.create_table(
        "deudas",
        sa.Column("id_deuda", sa.Integer(), nullable=False),
        sa.Column("id_cliente", sa.Integer(), nullable=False),
        sa.Column("id_venta", sa.Integer(), nullable=False),
        sa.Column("monto_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("saldo_pendiente", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("fecha_limite", sa.Date(), nullable=True),
        sa.Column(
            "creado_en", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "saldo_pendiente >= 0 AND saldo_pendiente <= monto_total",
            name=op.f("ck_deudas_saldo_valido"),
        ),
        sa.ForeignKeyConstraint(
            ["id_cliente"], ["clientes.id_cliente"], name=op.f("fk_deudas_id_cliente_clientes")
        ),
        sa.ForeignKeyConstraint(
            ["id_venta"], ["ventas.id_venta"], name=op.f("fk_deudas_id_venta_ventas")
        ),
        sa.PrimaryKeyConstraint("id_deuda", name=op.f("pk_deudas")),
        sa.UniqueConstraint("id_venta", name=op.f("uq_deudas_id_venta")),
    )
    op.create_index(op.f("ix_deudas_id_cliente"), "deudas", ["id_cliente"], unique=False)
    op.create_table(
        "abonos",
        sa.Column("id_abono", sa.Integer(), nullable=False),
        sa.Column("id_deuda", sa.Integer(), nullable=False),
        sa.Column("id_usuario", sa.Integer(), nullable=False),
        sa.Column("monto", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("metodo_pago", sa.String(length=15), nullable=False),
        sa.Column("nota", sa.String(length=255), nullable=True),
        sa.Column(
            "fecha", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "metodo_pago IN ('efectivo', 'tarjeta', 'transferencia')",
            name=op.f("ck_abonos_metodo_pago_valido"),
        ),
        sa.CheckConstraint("monto > 0", name=op.f("ck_abonos_monto_positivo")),
        sa.ForeignKeyConstraint(
            ["id_deuda"], ["deudas.id_deuda"], name=op.f("fk_abonos_id_deuda_deudas")
        ),
        sa.ForeignKeyConstraint(
            ["id_usuario"], ["usuarios.id_usuario"], name=op.f("fk_abonos_id_usuario_usuarios")
        ),
        sa.PrimaryKeyConstraint("id_abono", name=op.f("pk_abonos")),
    )
    op.create_index(op.f("ix_abonos_id_deuda"), "abonos", ["id_deuda"], unique=False)
    op.create_index(op.f("ix_abonos_id_usuario"), "abonos", ["id_usuario"], unique=False)
    op.create_table(
        "recordatorios_whatsapp",
        sa.Column("id_recordatorio", sa.Integer(), nullable=False),
        sa.Column("id_deuda", sa.Integer(), nullable=False),
        sa.Column(
            "enviado_en",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("estado", sa.String(length=10), nullable=False),
        sa.Column("id_mensaje_meta", sa.String(length=100), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "estado IN ('enviado', 'fallido')", name=op.f("ck_recordatorios_whatsapp_estado_valido")
        ),
        sa.ForeignKeyConstraint(
            ["id_deuda"],
            ["deudas.id_deuda"],
            name=op.f("fk_recordatorios_whatsapp_id_deuda_deudas"),
        ),
        sa.PrimaryKeyConstraint("id_recordatorio", name=op.f("pk_recordatorios_whatsapp")),
    )
    op.create_index(
        op.f("ix_recordatorios_whatsapp_id_deuda"),
        "recordatorios_whatsapp",
        ["id_deuda"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recordatorios_whatsapp_id_deuda"), table_name="recordatorios_whatsapp")
    op.drop_table("recordatorios_whatsapp")
    op.drop_index(op.f("ix_abonos_id_usuario"), table_name="abonos")
    op.drop_index(op.f("ix_abonos_id_deuda"), table_name="abonos")
    op.drop_table("abonos")
    op.drop_index(op.f("ix_deudas_id_cliente"), table_name="deudas")
    op.drop_table("deudas")
    op.drop_index(op.f("ix_detalle_venta_id_venta"), table_name="detalle_venta")
    op.drop_index(op.f("ix_detalle_venta_id_producto"), table_name="detalle_venta")
    op.drop_table("detalle_venta")
    op.drop_index(op.f("ix_ventas_id_usuario"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_id_negocio"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_id_cliente"), table_name="ventas")
    op.drop_index(op.f("ix_ventas_fecha"), table_name="ventas")
    op.drop_table("ventas")
    op.drop_index(op.f("ix_productos_nombre"), table_name="productos")
    op.drop_index(op.f("ix_productos_id_negocio"), table_name="productos")
    op.drop_index(op.f("ix_productos_id_categoria"), table_name="productos")
    op.drop_table("productos")
    op.drop_index(op.f("ix_usuarios_id_negocio"), table_name="usuarios")
    op.drop_table("usuarios")
    op.drop_index(op.f("ix_clientes_id_negocio"), table_name="clientes")
    op.drop_table("clientes")
    op.drop_index(op.f("ix_categorias_id_negocio"), table_name="categorias")
    op.drop_table("categorias")
    op.drop_table("negocios")
    # ### end Alembic commands ###
